//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public decimal id { get; set; }
        public string name { get; set; }
        public decimal countryId { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
